from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

# PUBLIC_INTERFACE
class ChatMessage(BaseModel):
    """Single chat message from a user."""
    role: str = Field(..., description="Role of sender, e.g., 'patient'.")
    content: str = Field(..., description="Text of the message.")

# PUBLIC_INTERFACE
class ChatRequest(BaseModel):
    """Chat request body containing session_id and the user message."""
    session_id: str = Field(..., description="Unique session identifier.")
    message: ChatMessage

# PUBLIC_INTERFACE
class ChatResponse(BaseModel):
    """Chat response from PatientAgent."""
    session_id: str
    reply: str
    notes: Dict[str, Any]

# PUBLIC_INTERFACE
class RecommendationRequest(BaseModel):
    """Request to generate recommendations based on a session and optional query."""
    session_id: str = Field(..., description="Session identifier to reference notes.")
    query: Optional[str] = Field(None, description="Optional query or context.")

# PUBLIC_INTERFACE
class RecommendationItem(BaseModel):
    """Single recommendation item."""
    type: str = Field(..., description="recommendation type: test/treatment/other")
    details: str = Field(..., description="Recommendation details.")
    rationale: Optional[str] = Field(None, description="Reasoning behind this recommendation.")

# PUBLIC_INTERFACE
class RecommendationResponse(BaseModel):
    """Recommendations generated by ClinicalAgent."""
    session_id: str
    recommendations: List[RecommendationItem]
    references: List[str]

# PUBLIC_INTERFACE
class ReportUploadResponse(BaseModel):
    """Response after uploading and parsing a report."""
    session_id: str
    filename: str
    extracted_text: str

# PUBLIC_INTERFACE
class GuidelinesUploadResponse(BaseModel):
    """Response after uploading guideline docs and indexing them."""
    files_indexed: List[str]
    total_chunks: int

# PUBLIC_INTERFACE
class GuidelinesQueryRequest(BaseModel):
    """Query guidelines using RAG."""
    query: str
    top_k: int = 3

# PUBLIC_INTERFACE
class GuidelinesQueryResponse(BaseModel):
    """RAG query results."""
    query: str
    results: List[Dict[str, Any]]
